### ISSUE TITLE
Not working in UILabel

### ISSUE THREAD

**Issue by quetool** [alexmx/AMXFontAutoScale#8] opened 2017-09-26 17:28 UTC
Hi, it's not working on UILabel (Swift 4)

![captura de pantalla 2017-09-26 a la s 14 26 53](https://user-images.githubusercontent.com/14978705/30874462-ca7e6d38-a2c6-11e7-8852-2f52f32f2389.png)

**Comment by alexmx** [comment] 2017-09-26 20:39
@quetool Thanks for reporting this.

Fixed the issue. Please update to [release 1.1.3](https://github.com/alexmx/AMXFontAutoScale/releases/tag/v1.1.3)

This bug is a duplicate of issue #7. But it seems that my fix for the previous release was just partial.

The root cause is a bug in the latest Swift compiler. The Swift JIRA ticket: [SR-5959](https://bugs.swift.org/browse/SR-5959)

Regards,
Alex

**Closed by alexmx** 2017-09-26 20:39 UTC
Labels: bug
