### ISSUE TITLE
AMXFontAutoScale - Landscape Support

### ISSUE THREAD

**Issue by KushThakkar** [alexmx/AMXFontAutoScale#6] opened 2017-09-05 14:45 UTC
I am getting issue in Landscape mode.
Font Size increase too much.

**Comment by alexmx** [comment] 2017-09-06 07:51
@KushThakkar Thanks for reporting this.

But I will need some additional information from you as I'am unable to reproduce this.
Can you please provide more details about your setup, which API from the library and which version of it are you using?

If you can record the issue or provide a demo project it would be great.

Regards,
Alex

**Comment by alexmx** [comment] 2017-09-12 08:44
Closing the issue for now because there is no feedback from the author.

**Closed by alexmx** 2017-09-12 08:44 UTC
